web/project/users/views.py
# project/users/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, request, redirect, url_for, flash, abort
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from flask_mail import Message
from threading import Thread
from itsdangerous import URLSafeTimedSerializer
from datetime import datetime
from twilio.rest import TwilioRestClient

from .forms import RegisterForm, LoginForm, EmailForm, PasswordForm, EditUserForm
from project import db, mail, app
from project.models import User


################
#### config ####
################

users_blueprint = Blueprint('users', __name__)


##########################
#### helper functions ####
##########################

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')


def send_async_email(msg):
    with app.app_context():
        mail.send(msg)


def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for(
        'users.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'email_confirmation.html',
        confirm_url=confirm_url)

    send_email('Confirm Your Email Address', [user_email], html)


def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    password_reset_url = url_for(
        'users.reset_with_token',
        token = password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
        _external=True)

    html = render_template(
        'email_password_reset.html',
        password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html)


def send_new_user_text_message(new_user_email):
    client = TwilioRestClient(app.config['ACCOUNT_SID'], app.config['AUTH_TOKEN'])
    message = client.messages.create(
        body="Kennedy Family Recipes... new user registered: {}".format(new_user_email),  # Message body, if any
        to=app.config['ADMIN_PHONE_NUMBER'],
        from_=app.config['TWILIO_PHONE_NUMBER']
    )
    # flash('Text message sent to {}: {}'.format(app.config['ADMIN_PHONE_NUMBER'], message.body), 'success')
    return


################
#### routes ####
################

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
                send_confirmation_email(new_user.email)
                if 'ACCOUNT_SID' in app.config and not app.config['TESTING']:
                    send_new_user_text_message(new_user.email)
                flash('Thanks for registering!  Please check your email to confirm your email address.', 'success')
                return redirect(url_for('recipes.user_recipes', recipe_type='All'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                user.last_logged_in = user.current_logged_in
                user.current_logged_in = datetime.now()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Thanks for logging in, {}'.format(current_user.email))
                return redirect(url_for('recipes.user_recipes', recipe_type='All'))
            else:
                flash('ERROR! Incorrect login credentials.', 'error')
    return render_template('login.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('recipes.public_recipes'))


@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=3600)
    except:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    user = User.query.filter_by(email=email).first()

    if user.email_confirmed:
        flash('Account already confirmed. Please login.', 'info')
    else:
        user.email_confirmed = True
        user.email_confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('Thank you for confirming your email address!', 'success')

    return redirect(url_for('recipes.public_recipes'))


@users_blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return render_template('password_reset_email.html', form=form)

        if user.email_confirmed:
            send_password_reset_email(user.email)
            flash('Please check your email for a password reset link.', 'success')
        else:
            flash('Your email address must be confirmed before attempting a password reset.', 'error')
        return redirect(url_for('users.login'))

    return render_template('password_reset_email.html', form=form)


@users_blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    except:
        flash('The password reset link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    form = PasswordForm()

    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return redirect(url_for('users.login'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_password_with_token.html', form=form, token=token)


@users_blueprint.route('/user_profile')
@login_required
def user_profile():
    return render_template('user_profile.html')


@users_blueprint.route('/email_change', methods=["GET", "POST"])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user
                    user.email = form.email.data
                    user.email_confirmed = False
                    user.email_confirmed_on = None
                    user.email_confirmation_sent_on = datetime.now()
                    db.session.add(user)
                    db.session.commit()
                    send_confirmation_email(user.email)
                    flash('Email changed!  Please confirm your new email address (link sent to new email).', 'success')
                    return redirect(url_for('users.user_profile'))
                else:
                    flash('Sorry, that email already exists!', 'error')
            except IntegrityError:
                flash('Error! That email already exists!', 'error')
    return render_template('email_change.html', form=form)


@users_blueprint.route('/password_change', methods=["GET", "POST"])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('Password has been updated!', 'success')
            return redirect(url_for('users.user_profile'))

    return render_template('password_change.html', form=form)


@users_blueprint.route('/resend_confirmation')
@login_required
def resend_email_confirmation():
    try:
        send_confirmation_email(current_user.email)
        flash('Email sent to confirm your email address.  Please check your email!', 'success')
    except IntegrityError:
        flash('Error!  Unable to send email to confirm your email address.', 'error')

    return redirect(url_for('users.user_profile'))


@users_blueprint.route('/admin_view_users')
@login_required
def admin_view_users():
    if current_user.role != 'admin':
        abort(403)

web/project/templates/410.html
{% extends "layout.html" %}

{% block content %}

  <h1>Gone</h1>
  <h4>The target resource is no longer available at the origin server and that this condition is likely to be permanent.</h4>
  <h4><a href="{{ url_for('recipes.public_recipes') }}">Kennedy Family Recipes</a></h4>

{% endblock %}

web/project/templates/_form_macros.html
{% macro render_field(field) %}
  <dt>{{ field.label }}:
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_field_without_label(field) %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_boolean_field(field) %}
  <dd>{{ field(**kwargs)|safe }} {{ field.label }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_errors(field) %}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
{% endmacro %}


{% macro render_recipe_edit_form(form, recipe) %}
    <div class="form-group row">
      <legend for="recipe_title" class="col-form-legend col-sm-2">Title</legend>
      <div class="col-sm-6">
        <input type="text" class="form-control" id="recipe_title" name="recipe_title" value="{{ recipe.recipe_title }}">
        {{ render_errors(form.recipe_title) }}
      </div>
    </div>

    <div class="form-group row">
      <legend for="recipe_description" class="col-form-legend col-sm-2">Description</legend>
      <div class="col-sm-6">
        <input type="text" class="form-control" id="recipe_description" name="recipe_description" value="{{ recipe.recipe_description }}">
        {{ render_errors(form.recipe_description) }}
      </div>
    </div>

    <fieldset class="form-group row">
      <legend for="recipe_type" class="col-form-legend col-sm-2">Recipe Type</legend>
      <div class="col-sm-6">
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.recipe_type == "Breakfast" %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-0" value="Breakfast" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-0" value="Breakfast">
              {% endif %}
              Breakfast
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.recipe_type == "Lunch" %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-1" value="Lunch" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-1" value="Lunch">
              {% endif %}
              Lunch
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.recipe_type == "Dinner" %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-2" value="Dinner" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-2" value="Dinner">
              {% endif %}
              Dinner
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.recipe_type == "Dessert" %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-3" value="Dessert" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-3" value="Dessert">
              {% endif %}
              Dessert
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.recipe_type == "Side Dish" %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-4" value="Side Dish" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-4" value="Side Dish">
              {% endif %}
              Side Dish
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.recipe_type == "Drink" %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-5" value="Drink" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_type" id="recipe_type-5" value="Drink">
              {% endif %}
              Drink
            </label>
          </div>
          {{ render_errors(form.recipe_type) }}
      </div>
    </fieldset>

    <fieldset class="form-group row">
      <legend for="recipe_rating" class="col-form-legend col-sm-2">Rating</legend>
      <div class="col-sm-6">
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.rating == 1 %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-0" value="1" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-0" value="1">
              {% endif %}
              1 (Worst)
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.rating == 2 %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-1" value="2" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-1" value="2">
              {% endif %}
              2
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.rating == 3 %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-2" value="3" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-2" value="3">
              {% endif %}
              3
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.rating == 4 %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-3" value="4" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-3" value="4">
              {% endif %}
              4
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.rating == 5 %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-4" value="5" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-4" value="5">
              {% endif %}
              5
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.rating == 5 %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-5" value="6" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-5" value="6">
              {% endif %}
              6
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.rating == 5 %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-6" value="7" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-6" value="7">
              {% endif %}
              7
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.rating == 5 %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-7" value="8" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-7" value="8">
              {% endif %}
              8
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.rating == 5 %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-8" value="9" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-8" value="9">
              {% endif %}
              9
            </label>
          </div>
          <div class="form-check">
            <label class="form-check-label">
              {% if recipe.rating == 5 %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-9" value="10" checked>
              {% else %}
                <input type="radio" class="form-check-input" name="recipe_rating" id="recipe_rating-9" value="10">
              {% endif %}
              10 (Best)
            </label>
          </div>
          {{ render_errors(form.recipe_rating) }}
      </div>
    </fieldset>

    <div class="form-group row">
      <legend for="recipe_public" class="col-form-legend col-sm-2">Public Recipe?</legend>
      <div class="col-sm-6">
        <div class="form-check">
          <label class="form-check-label">
            {% if recipe.is_public == true %}
              <input class="form-check-input" name="recipe_public" id="recipe_public" type="checkbox" checked>
            {% else %}
              <input class="form-check-input" name="recipe_public" id="recipe_public" type="checkbox">
            {% endif %}
            Yes
          </label>
          {{ render_errors(form.recipe_public) }}
        </div>
      </div>
    </div>

    <div class="form-group row">
      <legend for="recipe_dairy_free" class="col-form-legend col-sm-2">Dairy-Free Recipe?</legend>
      <div class="col-sm-6">
        <div class="form-check">
          <label class="form-check-label">
            {% if recipe.dairy_free_recipe == true %}
              <input class="form-check-input" name="recipe_dairy_free" id="recipe_dairy_free" type="checkbox" checked>
            {% else %}
              <input class="form-check-input" name="recipe_dairy_free" id="recipe_dairy_free" type="checkbox">
            {% endif %}
            Yes
          </label>
          {{ render_errors(form.recipe_dairy_free) }}
        </div>
      </div>
    </div>

    <div class="form-group row">
      <legend for="recipe_soy_free" class="col-form-legend col-sm-2">Soy-Free Recipe?</legend>
      <div class="col-sm-6">
        <div class="form-check">
          <label class="form-check-label">
            {% if recipe.soy_free_recipe == true %}
              <input class="form-check-input" name="recipe_soy_free" id="recipe_soy_free" type="checkbox" checked>
            {% else %}
              <input class="form-check-input" name="recipe_soy_free" id="recipe_soy_free" type="checkbox">
            {% endif %}
            Yes
          </label>
          {{ render_errors(form.recipe_soy_free) }}
        </div>
      </div>
    </div>

    <div class="form-group row">
      <legend for="recipe_image" class="col-form-legend col-sm-2">Recipe Image</legend>
      <div class="col-sm-6">
        <label class="form-check-label">Current filename: {{ recipe.image_filename }}</label>
        <input type="file" class="form-control-file" name="recipe_image" id="recipe_image" aria-describedby="fileHelp">
        <small id="fileHelp" class="form-text text-muted">Select an image for this recipe.</small>
        {{ render_errors(form.recipe_image) }}
      </div>
    </div>

    <div class="form-group row">
      <legend for="recipe_ingredients" class="col-form-legend col-sm-2">Ingredients</legend>
      <div class="col-sm-6">
        <textarea class="form-control" name="recipe_ingredients" id="recipe_ingredients" rows="8">{{ recipe.ingredients }}</textarea>
        {{ render_errors(form.recipe_ingredients) }}
      </div>
    </div>

    <div class="form-group row">
      <legend for="recipe_steps" class="col-form-legend col-sm-2">Steps</legend>
      <div class="col-sm-6">
        <textarea class="form-control" name="recipe_steps" id="recipe_steps" rows="8">{{ recipe.recipe_steps }}</textarea>
        {{ render_errors(form.recipe_steps) }}
      </div>
    </div>

    <div class="form-group row">
      <legend for="recipe_inspiration" class="col-form-legend col-sm-2">Inspiration</legend>
      <div class="col-sm-6">
        <input type="text" class="form-control" id="recipe_inspiration" name="recipe_inspiration" value="{{ recipe.inspiration }}">
        {{ render_errors(form.recipe_inspiration) }}
      </div>
    </div>
{% endmacro %}

web/project/templates/admin_view_users.html
{% extends "layout.html" %}

{% block content %}

<div class="admin-view-users">
  <div class="page-header">
    <h2>Administrative Page: List of Users</h2>
  </div>

  <div class="row">
    <table class="table table-striped" id="admin_list_of_users">
      <thead>
        <tr>
          <th>User ID</th>
          <th>Email</th>
          <th>Role</th>
          <th>Registration Date</th>
          <th>Email Confirmed?</th>
          <th>Email Confirmed On</th>
          <th>Last Login</th>
          <th>Actions</th>
          </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td> {{ user.id }} </td>
            <td> {{ user.email }} </td>
            <td> {{ user.role }} </td>
            <td> {{ user.registered_on }} </td>
            <td> {{ user.email_confirmed }} </td>
            <td> {{ user.email_confirmed_on }} </td>
            <td> {{ user.last_logged_in }} </td>
            <td>
              <a href="{{ url_for('users.admin_delete_user', user_id = user.id) }}">Delete</a>
              <a href="{{ url_for('users.admin_edit_user', user_id = user.id) }}">Edit</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

web/project/templates/email_change.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field_without_label %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>Email Change</h2>
  </div>

  <p>Current Email: {{ current_user.email }}</p>
  <p>Please enter your new email address:</p>
  <form action="{{ url_for('users.user_email_change') }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field_without_label(form.email, placeholder="Enter New Email Address") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>

{% endblock %}

web/project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Kennedy Family Recipe App">
    <meta name="author" content="Patrick Kennedy">
    <title>Kennedy Family Recipe App</title>
    <!-- styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#recipes-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('recipes.public_recipes') }}">Kennedy Family Recipes</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="recipes-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Breakfast') }}">Breakfast</a></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Lunch') }}">Lunch</a></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Dinner') }}">Dinner</a></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Dessert') }}">Dessert</a></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Side Dish') }}">Side Dish</a></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='Drink') }}">Drink</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ url_for('recipes.user_recipes', recipe_type='All') }}">All Recipes</a></li>
              </ul>
            </li>
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('recipes.add_recipe') }}">Add Recipe</a></li>
              <li><a href="{{ url_for('recipes.whats_for_dinner') }}">What's for Dinner?</a></li>
              <li><a href="{{ url_for('users.logout') }}">Log Out</a></li>
              {% if current_user.role == "admin" %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ url_for('users.admin_view_users') }}">Users</a></li>
                    <li><a href="{{ url_for('recipes.admin_view_recipes') }}">Recipes</a></li>
                    <li><a href="#">Blog</a></li>
                  </ul>
                </li>
              {% endif %}
            {% else %}
              <li><a href="{{ url_for('users.register') }}">Register</a></li>
              <li><a href="{{ url_for('users.login') }}">Log In</a></li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('users.user_profile') }}">{{current_user.email}}</a></li>
            {% else %}
              <li><a href="#">Welcome!</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </nav>

    <div class="container">
      <div class="content">

        <!-- flash messages -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
          <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
        {% endfor %}

        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
          <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
        {% endfor %}

        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
          <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
        {% endfor %}

<!--
        {% for debug_message in get_flashed_messages(category_filter=["debug"]) %}
          <div class="alert alert-info alert-dismissible">{{ debug_message }}</div>
        {% endfor %}
-->
        <!-- child template -->
        {% block content %}
        {% endblock %}

      </div>
      <div class="footer">
        <hr>
        <p>Patrick Kennedy - 2017</p>
      </div>
    </div><!-- /.container -->

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

web/project/templates/password_reset_email.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="add-recipe">
  <div class="page-header">
    <h2>Email Address:</h2>
  </div>
  <form action="{{ url_for('users.reset') }}" method="POST">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Enter Email Address") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Submit</button>
  </form>
</div>

{% endblock %}